name: Bug Report
description: File a bug report
labels: ["bug"]

body:
- type: textarea
  id: bug_details
  attributes:
    label: Cause of the bug
    description: Tell us in detail what exactly causes this bug
    placeholder: "Example: this bug happens when opening **X**"
  validations:
    required: true

- type: dropdown
  id: bug_platform
  attributes:
    label: Your Platform
    description: In which platform did you face this bug?
    multiple: false
    options:
    - "Windows"
    - "MacOS"
    - "Linux (Ubuntu, Fedora, Arch)"
    - "HTML5"
