name: Suggestion
description: Suggest something for the engine.
labels: ["suggestion"]

body:
  - type: textarea
    id: suggestion_details
    attributes:
      label: Idea you want to suggest
      placeholder: "Example: Can we have mp4 cutscenes?"
    validations:
      required: true
